### ISSUE TITLE
How to learn SRT radix-4 divider?

### ISSUE THREAD

**Issue by ShangChuanhe** [wzc810049078/SRT-4-DIVISION#1]
I can find little systematic information on the internet and know little about the SRT radix-4 divider. I hope you can share some learning experiences or literature.

**Comment by wzc810049078** [comment]
可以看看这些书
<img width="343" alt="image" src="https://github.com/wzc810049078/SRT-4-DIVISION/assets/39558469/08216744-461f-4248-be97-9845aa6ba14d">

**Comment by ShangChuanhe** [comment]
这些资料我都有看过，但是对于将理论变成实际的电路其实还有很长的路要走。虽然现在已经弄明白SRT radix-4的原理，但其实也只是浅层理解，还未到达通透的程度。能否留一个联系邮箱，再有不懂的东西可以向你请教？
